/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.UIManager;
import representation.DescCaso;

/**
 *
 * @author Zilly
 */
public class CasoGUI extends javax.swing.JFrame {
    
    private DescCaso descCaso;
    
    /**
     * Creates new form Caso
     * @param descCaso
     */
    public CasoGUI(DescCaso descCaso) {
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        
        this.descCaso = descCaso;
        
        initComponents();
        setaValores();
    }

    private void setaValores(){
        jLabelTitulo.setText("Caso de id " + descCaso.getCasoId().toString());
        jLabelCarta1.setText("Carta 1: " + descCaso.getCarta1().toString());
        jLabelCarta2.setText("Carta 2: " + descCaso.getCarta2().toString());
        jLabelCarta3.setText("Carta 3: " + descCaso.getCarta3().toString());
        jLabelGanheiEnvido.setText("Ganhei o Envido: " + descCaso.getGanheiEnvido().toString());
        jLabelGanheiVolta.setText("Ganhei a Volta: " + descCaso.getGanheiVolta().toString());
        jLabelPontosMeus.setText("Pontos Meus: " + descCaso.getPontosMeus().toString());
        jLabelPontosAdv.setText("Pontos Adv: " + descCaso.getPontosAdv().toString());
        
        jLabelR1CartaMinha.setText("Carta Minha: " + descCaso.getR1CartaMinha().toString());
        jLabelR1CartaAdv.setText("Carta Adv: " + descCaso.getR1CartaAdv().toString());
        jLabelR1PediuEnvido.setText("Pediu Envido: " + descCaso.getR1PediuEnvido().toString());
        jLabelR1AceitouEnvido.setText("Aceitou Envido: " + descCaso.getR1AceitouEnvido().toString());
        jLabelR1PediuTruco.setText("Pediu Truco: " + descCaso.getR1PediuTruco().toString());
        jLabelR1AceitouTruco.setText("Aceitou Truco: " + descCaso.getR1AceitouTruco().toString());
        jLabelR1PediuRetruco.setText("Pediu Retruco: " + descCaso.getR1PediuRetruco().toString());
        jLabelR1AceitouRetruco.setText("Aceitou Retruco: " + descCaso.getR1AceitouRetruco().toString());
        jLabelR1PediuValeQuatro.setText("Pediu Vale 4: " + descCaso.getR1PediuValeQuatro().toString());
        jLabelR1AceitouValeQuatro.setText("Aceitou Vale 4: " + descCaso.getR1AceitouValeQuatro().toString());
        
        jLabelR2CartaMinha.setText("Carta Minha: " + descCaso.getR2CartaMinha().toString());
        jLabelR2CartaAdv.setText("Carta Adv: " + descCaso.getR2CartaAdv().toString());
        jLabelR2PediuTruco.setText("Pediu Truco: " + descCaso.getR2PediuTruco().toString());
        jLabelR2AceitouTruco.setText("Aceitou Truco: " + descCaso.getR2AceitouTruco().toString());
        jLabelR2PediuRetruco.setText("Pediu Retruco: " + descCaso.getR2PediuRetruco().toString());
        jLabelR2AceitouRetruco.setText("Aceitou Retruco: " + descCaso.getR2AceitouRetruco().toString());
        jLabelR2PediuValeQuatro.setText("Pediu Vale 4: " + descCaso.getR2PediuValeQuatro().toString());
        jLabelR2AceitouValeQuatro.setText("Aceitou Vale 4: " + descCaso.getR2AceitouValeQuatro().toString());
        
        jLabelR3CartaMinha.setText("Carta Minha: " + descCaso.getR3CartaMinha().toString());
        jLabelR3CartaAdv.setText("Carta Adv: " + descCaso.getR3CartaAdv().toString());
        jLabelR3PediuTruco.setText("Pediu Truco: " + descCaso.getR3PediuTruco().toString());
        jLabelR3AceitouTruco.setText("Aceitou Truco: " + descCaso.getR3AceitouTruco().toString());
        jLabelR3PediuRetruco.setText("Pediu Retruco: " + descCaso.getR3PediuRetruco().toString());
        jLabelR3AceitouRetruco.setText("Aceitou Retruco: " + descCaso.getR3AceitouRetruco().toString());
        jLabelR3PediuValeQuatro.setText("Pediu Vale 4: " + descCaso.getR3PediuValeQuatro().toString());
        jLabelR3AceitouValeQuatro.setText("Aceitou Vale 4: " + descCaso.getR3AceitouValeQuatro().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCarta1 = new javax.swing.JLabel();
        jLabelCarta2 = new javax.swing.JLabel();
        jLabelCarta3 = new javax.swing.JLabel();
        jLabelGanheiEnvido = new javax.swing.JLabel();
        jLabelGanheiVolta = new javax.swing.JLabel();
        jLabelPontosMeus = new javax.swing.JLabel();
        jLabelPontosAdv = new javax.swing.JLabel();
        jLabelR1AceitouEnvido = new javax.swing.JLabel();
        jLabelR1PediuTruco = new javax.swing.JLabel();
        jLabelR1AceitouTruco = new javax.swing.JLabel();
        jLabelR1PediuRetruco = new javax.swing.JLabel();
        jLabelR1AceitouRetruco = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelR1PediuEnvido = new javax.swing.JLabel();
        jLabelR1PediuValeQuatro = new javax.swing.JLabel();
        jLabelR1AceitouValeQuatro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelR2PediuValeQuatro = new javax.swing.JLabel();
        jLabelR2AceitouRetruco = new javax.swing.JLabel();
        jLabelR2AceitouValeQuatro = new javax.swing.JLabel();
        jLabelR2PediuTruco = new javax.swing.JLabel();
        jLabelR2AceitouTruco = new javax.swing.JLabel();
        jLabelR2PediuRetruco = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelR3PediuValeQuatro = new javax.swing.JLabel();
        jLabelR3AceitouRetruco = new javax.swing.JLabel();
        jLabelR3AceitouValeQuatro = new javax.swing.JLabel();
        jLabelR3PediuTruco = new javax.swing.JLabel();
        jLabelR3AceitouTruco = new javax.swing.JLabel();
        jLabelR3PediuRetruco = new javax.swing.JLabel();
        jLabelR1CartaMinha = new javax.swing.JLabel();
        jLabelR1CartaAdv = new javax.swing.JLabel();
        jLabelR2CartaMinha = new javax.swing.JLabel();
        jLabelR2CartaAdv = new javax.swing.JLabel();
        jLabelR3CartaAdv = new javax.swing.JLabel();
        jLabelR3CartaMinha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelTitulo.setText("jLabelTitulo");

        jLabelCarta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarta1.setText("jLabelCarta1");

        jLabelCarta2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarta2.setText("jLabelCarta2");

        jLabelCarta3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarta3.setText("jLabelCarta3");

        jLabelGanheiEnvido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGanheiEnvido.setText("jLabelGanheiEnvido");

        jLabelGanheiVolta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGanheiVolta.setText("jLabelGanheiVolta");

        jLabelPontosMeus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPontosMeus.setText("jLabelPontosMeus");

        jLabelPontosAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPontosAdv.setText("jLabelPontosAdv");

        jLabelR1AceitouEnvido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1AceitouEnvido.setText("jLabelR1AceitouEnvido");

        jLabelR1PediuTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1PediuTruco.setText("jLabelR1PediuTruco");

        jLabelR1AceitouTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1AceitouTruco.setText("jLabelR1AceitouTruco");

        jLabelR1PediuRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1PediuRetruco.setText("jLabelR1PediuRetruco");

        jLabelR1AceitouRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1AceitouRetruco.setText("jLabelR1AceitouRetruco");

        jLabelR1PediuEnvido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1PediuEnvido.setText("jLabelR1PediuEnvido");

        jLabelR1PediuValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1PediuValeQuatro.setText("jLabelR1PediuValeQuatro");

        jLabelR1AceitouValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1AceitouValeQuatro.setText("jLabelR1AceitouValeQuatro");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dados da Volta:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dados da Rodada 1:");

        jLabelR2PediuValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2PediuValeQuatro.setText("jLabelR2PediuValeQuatro");

        jLabelR2AceitouRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2AceitouRetruco.setText("jLabelR2AceitouRetruco");

        jLabelR2AceitouValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2AceitouValeQuatro.setText("jLabelR2AceitouValeQuatro");

        jLabelR2PediuTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2PediuTruco.setText("jLabelR2PediuTruco");

        jLabelR2AceitouTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2AceitouTruco.setText("jLabelR2AceitouTruco");

        jLabelR2PediuRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2PediuRetruco.setText("jLabelR2PediuRetruco");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dados da Rodada 2:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dados da Rodada 3:");

        jLabelR3PediuValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3PediuValeQuatro.setText("jLabelR3PediuValeQuatro");

        jLabelR3AceitouRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3AceitouRetruco.setText("jLabelR3AceitouRetruco");

        jLabelR3AceitouValeQuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3AceitouValeQuatro.setText("jLabelR3AceitouValeQuatro");

        jLabelR3PediuTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3PediuTruco.setText("jLabelR3PediuTruco");

        jLabelR3AceitouTruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3AceitouTruco.setText("jLabelR3AceitouTruco");

        jLabelR3PediuRetruco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3PediuRetruco.setText("jLabelR3PediuRetruco");

        jLabelR1CartaMinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1CartaMinha.setText("jLabelR1CartaMinha");

        jLabelR1CartaAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR1CartaAdv.setText("jLabelR1CartaAdv");

        jLabelR2CartaMinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2CartaMinha.setText("jLabelR2CartaMinha");

        jLabelR2CartaAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR2CartaAdv.setText("jLabelR2CartaAdv");

        jLabelR3CartaAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3CartaAdv.setText("jLabelR3CartaAdv");

        jLabelR3CartaMinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelR3CartaMinha.setText("jLabelR3CartaMinha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCarta1)
                            .addComponent(jLabelCarta2)
                            .addComponent(jLabelCarta3)
                            .addComponent(jLabelGanheiEnvido)
                            .addComponent(jLabelGanheiVolta)
                            .addComponent(jLabelPontosMeus)
                            .addComponent(jLabelPontosAdv)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelR1PediuValeQuatro)
                            .addComponent(jLabelR1AceitouEnvido)
                            .addComponent(jLabelR1PediuTruco)
                            .addComponent(jLabelR1AceitouTruco)
                            .addComponent(jLabelR1PediuRetruco)
                            .addComponent(jLabelR1AceitouRetruco)
                            .addComponent(jLabelR1AceitouValeQuatro)
                            .addComponent(jLabelR1PediuEnvido)
                            .addComponent(jLabelR1CartaAdv)
                            .addComponent(jLabelR1CartaMinha)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelR2AceitouRetruco)
                            .addComponent(jLabelR2AceitouValeQuatro)
                            .addComponent(jLabelR2PediuTruco)
                            .addComponent(jLabelR2AceitouTruco)
                            .addComponent(jLabelR2PediuRetruco)
                            .addComponent(jLabelR2CartaMinha)
                            .addComponent(jLabelR2CartaAdv)
                            .addComponent(jLabelR2PediuValeQuatro)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelR3AceitouTruco)
                            .addComponent(jLabelR3PediuRetruco)
                            .addComponent(jLabelR3AceitouValeQuatro)
                            .addComponent(jLabelR3PediuValeQuatro)
                            .addComponent(jLabelR3AceitouRetruco)
                            .addComponent(jLabelR3PediuTruco)
                            .addComponent(jLabelR3CartaMinha)
                            .addComponent(jLabelR3CartaAdv)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCarta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGanheiEnvido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGanheiVolta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPontosAdv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPontosMeus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelR2CartaMinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2CartaAdv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2PediuTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2AceitouTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2PediuRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2AceitouRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2PediuValeQuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2AceitouValeQuatro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelR3CartaMinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3CartaAdv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3PediuTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3AceitouTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3PediuRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3AceitouRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3PediuValeQuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR3AceitouValeQuatro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelR1CartaMinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1CartaAdv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1PediuEnvido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1AceitouEnvido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1PediuTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1AceitouTruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1PediuRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1AceitouRetruco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1PediuValeQuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR1AceitouValeQuatro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CasoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CasoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CasoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CasoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CasoGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCarta1;
    private javax.swing.JLabel jLabelCarta2;
    private javax.swing.JLabel jLabelCarta3;
    private javax.swing.JLabel jLabelGanheiEnvido;
    private javax.swing.JLabel jLabelGanheiVolta;
    private javax.swing.JLabel jLabelPontosAdv;
    private javax.swing.JLabel jLabelPontosMeus;
    private javax.swing.JLabel jLabelR1AceitouEnvido;
    private javax.swing.JLabel jLabelR1AceitouRetruco;
    private javax.swing.JLabel jLabelR1AceitouTruco;
    private javax.swing.JLabel jLabelR1AceitouValeQuatro;
    private javax.swing.JLabel jLabelR1CartaAdv;
    private javax.swing.JLabel jLabelR1CartaMinha;
    private javax.swing.JLabel jLabelR1PediuEnvido;
    private javax.swing.JLabel jLabelR1PediuRetruco;
    private javax.swing.JLabel jLabelR1PediuTruco;
    private javax.swing.JLabel jLabelR1PediuValeQuatro;
    private javax.swing.JLabel jLabelR2AceitouRetruco;
    private javax.swing.JLabel jLabelR2AceitouTruco;
    private javax.swing.JLabel jLabelR2AceitouValeQuatro;
    private javax.swing.JLabel jLabelR2CartaAdv;
    private javax.swing.JLabel jLabelR2CartaMinha;
    private javax.swing.JLabel jLabelR2PediuRetruco;
    private javax.swing.JLabel jLabelR2PediuTruco;
    private javax.swing.JLabel jLabelR2PediuValeQuatro;
    private javax.swing.JLabel jLabelR3AceitouRetruco;
    private javax.swing.JLabel jLabelR3AceitouTruco;
    private javax.swing.JLabel jLabelR3AceitouValeQuatro;
    private javax.swing.JLabel jLabelR3CartaAdv;
    private javax.swing.JLabel jLabelR3CartaMinha;
    private javax.swing.JLabel jLabelR3PediuRetruco;
    private javax.swing.JLabel jLabelR3PediuTruco;
    private javax.swing.JLabel jLabelR3PediuValeQuatro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
